# 📘 Ejercicios de Arrays y Matrices con NumPy
---Este notebook contiene ejercicios prácticos para trabajar con **arrays y matrices en NumPy**.
Completa cada celda de código con la solución correspondiente.

**Ejercicio 1:** Crear un array de 10 elementos con ceros.

# Sección nueva

In [ ]:
import numpy as np

arr1 = np.zeros(10)

print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Ejercicio 2:** Genera un array con los números del 1 al 20.

In [ ]:
# Tu código aquí
arr2 = np.arange(1, 21)
print(arr2)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


**Ejercicio 3:** Crea un array con los números pares del 2 al 50.

In [ ]:
# Tu código aquí
arr3 = np.arange(2, 51, 2)
print(arr3)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


**Ejercicio 4:** Genera un array de tamaño 8 donde todos los valores sean 7.

In [ ]:
# Tu código aquí
arr4 = np.full(8, 7)
print(arr4)

[7 7 7 7 7 7 7 7]


**Ejercicio 5:** Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.

In [ ]:
# Tu código aquí
arr5 = np.random.rand(4,4)
print(arr5)

[[0.55487988 0.71141492 0.52410883 0.12654164]
 [0.32027353 0.85836939 0.4172854  0.54459283]
 [0.24067396 0.02413309 0.25343954 0.33824959]
 [0.86964696 0.6645967  0.67317847 0.09693485]]


**Ejercicio 6:** Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# Tu código aquí
suma = a + b
print(suma)


[5 7 9]


**Ejercicio 7:** Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.

In [ ]:
# Tu código aquí
A = np.random.randint(1, 11, (3,3))
B = np.random.randint(1, 11, (3,3))
print("Matriz A:\n", A)
print("Matriz B:\n", B)

# Multiplicación matricial
C = A @ B   # también podés usar: np.dot(A, B)
print("Resultado de A x B:\n", C)

Matriz A:
 [[ 5 10 10]
 [ 8  9  5]
 [ 2  3  9]]
Matriz B:
 [[9 6 7]
 [2 4 6]
 [5 8 9]]
Resultado de A x B:
 [[115 150 185]
 [115 124 155]
 [ 69  96 113]]


**Ejercicio 8:** Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.

In [ ]:
# Tu código aquí
arr8 = np.random.randint(1, 101, 15)
print("Array generado:\n", arr8)

print("Máximo:", arr8.max())
print("Mínimo:", arr8.min())
print("Promedio:", arr8.mean())


Array generado:
 [73 53 78 73 58 10 90 35  9 74 77 89 56 72 46]
Máximo: 90
Mínimo: 9
Promedio: 59.53333333333333


**Ejercicio 9:** Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.

In [ ]:
# Tu código aquí
arr9 = np.arange(1, 26).reshape(5, 5)
print("Matriz 5x5:\n", arr9)

diagonal = np.diag(arr9)
print("Diagonal de la matriz:", diagonal)

Matriz 5x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal de la matriz: [ 1  7 13 19 25]


**Ejercicio 10
:** Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna.

In [ ]:
# Tu código aquí
arr10 = np.random.randint(1, 21, (5,5))
print("Matriz 5x5:\n", arr10)

suma_filas = arr10.sum(axis=1)
print("Suma de cada fila:", suma_filas)

suma_columnas = arr10.sum(axis=0)
print("Suma de cada columna:", suma_columnas)

Matriz 5x5:
 [[ 1 11 19 16  9]
 [ 4  1 15 17  1]
 [17 20  3 16 20]
 [12  7 12 12 19]
 [19  6 17 17  4]]
Suma de cada fila: [56 38 76 62 63]
Suma de cada columna: [53 45 66 78 53]
